services:
  db:
    image: postgres:14
    container_name: techquire_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techquire_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: techquire_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db # The hostname is the service name "db" in Docker Compose
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: techquire_db
    # If you need environment variables for other things, add them here

volumes:
  db_data:
